spring.datasource.username=sa
spring.datasource.password=t
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.datasource.url=${DATASOURCE_URL:jdbc:h2:mem:chappl}/${DATASOURCE_DBNAME}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.${DATASOURCE_TYPE:H2}Dialect
spring.jpa.show-sql=true